project_id = "jboartixfhvifdecdufq"

[functions.claim-domain]
verify_jwt = false

[functions.sync-cancelled-accounts]
verify_jwt = false

[functions.confirm-all-users]
verify_jwt = false

[functions.check-subscription-history]
verify_jwt = false

[functions.receive-purchase-webhook]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.activecampaign-api]
verify_jwt = false

[functions.brevo-api]
verify_jwt = false

[functions.brevo-new-registration]
verify_jwt = false

[functions.cancel-subscription]
verify_jwt = false

[functions.check-domain-status]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.check-verification-code]
verify_jwt = false

[functions.cleanup-inactive-apps]
verify_jwt = false

[functions.complete-registration]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.delete-user-account]
verify_jwt = false

[functions.domain-lookup]
verify_jwt = false

[functions.get-app-owner-status]
verify_jwt = false

[functions.get-stripe-subscription-status]
verify_jwt = false

[functions.google-drive-upload]
verify_jwt = false

[functions.reactivate-subscription]
verify_jwt = false

[functions.resend-verification-code]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.send-access-email]
verify_jwt = false

[functions.send-custom-email]
verify_jwt = false

[functions.send-order-bump-code]
verify_jwt = false

[functions.send-password-reset-code]
verify_jwt = false

[functions.send-password-reset-link]
verify_jwt = false

[functions.send-password-setup-email]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.validate-product]
verify_jwt = false

[functions.verify-code]
verify_jwt = false

[functions.verify-custom-domain]
verify_jwt = false

[functions.verify-order-bump-code]
verify_jwt = false

[functions.verify-password-reset-code]
verify_jwt = false

[functions.pdf-proxy]
verify_jwt = false
